# Generated by Django 2.1.4 on 2018-12-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='image_fullsize',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='title',
            field=models.CharField(default='Title', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gisportfoliopiece',
            name='summary',
            field=models.CharField(max_length=120),
        ),
    ]
