# Generated by Django 2.1.4 on 2018-12-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0002_auto_20181211_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gisportfoliopiece',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gisportfoliopiece',
            name='image_fullsize',
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='file_to_download',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='full_text',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='image_med',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='image_thumb',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/'),
            preserve_default=False,
        ),
    ]
