# Generated by Django 2.1.4 on 2018-12-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0003_auto_20181211_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisportfoliopiece',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
