# Generated by Django 2.1.4 on 2018-12-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0004_auto_20181211_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='file_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
