# Generated by Django 2.1.4 on 2018-12-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0005_auto_20181211_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='piece_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
