# Generated by Django 2.1.4 on 2018-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0006_gisportfoliopiece_piece_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='date_created',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
