# Generated by Django 2.1.4 on 2018-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0007_gisportfoliopiece_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gisportfoliopiece',
            old_name='file_to_download',
            new_name='item1_file_to_download',
        ),
        migrations.RenameField(
            model_name='gisportfoliopiece',
            old_name='image_med',
            new_name='item1_image_med',
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='item2_file_to_download',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='item2_image_med',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='item3_file_to_download',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gisportfoliopiece',
            name='item3_image_med',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
    ]
