# Generated by Django 2.1.4 on 2018-12-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0008_auto_20181211_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=120)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('image_thumb', models.ImageField(upload_to='images/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='PortItemPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('summary', models.CharField(max_length=120)),
                ('image_thumb', models.ImageField(upload_to='images/%Y/%m/')),
                ('image_med', models.ImageField(upload_to='images/%Y/%m/')),
                ('file_to_download', models.FileField(blank=True, null=True, upload_to='images/%Y/%m/')),
                ('file_format', models.CharField(blank=True, max_length=20, null=True)),
                ('piece_print_size', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.CharField(blank=True, max_length=18, null=True)),
                ('parent_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_portfolio_pieces.PortItem')),
            ],
        ),
        migrations.DeleteModel(
            name='GisPortfolioPiece',
        ),
    ]
