# Generated by Django 2.1.4 on 2018-12-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0009_auto_20181214_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portitempiece',
            name='image_thumb',
        ),
    ]
