# Generated by Django 2.1.4 on 2018-12-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0010_remove_portitempiece_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='portitempiece',
            name='piece_file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
