# Generated by Django 2.1.4 on 2018-12-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0011_portitempiece_piece_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitempiece',
            name='parent_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gis_portfolio_pieces.PortItem'),
        ),
    ]
