# Generated by Django 2.1.4 on 2018-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0012_auto_20181214_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portitempiece',
            name='date_created',
        ),
        migrations.AddField(
            model_name='portitem',
            name='date_created',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
