# Generated by Django 2.1.4 on 2018-12-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0013_auto_20181214_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitempiece',
            name='summary',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
