# Generated by Django 2.1.4 on 2018-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0014_auto_20181214_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitempiece',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
