# Generated by Django 2.1.4 on 2018-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0015_auto_20181214_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='portitempiece',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
