# Generated by Django 2.1.4 on 2018-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0016_portitempiece_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portitem',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
