# Generated by Django 2.1.4 on 2018-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0016_auto_20181216_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitem',
            name='image_thumb',
            field=models.ImageField(upload_to='../../public_html/static_media/images/%Y/%m/'),
        ),
    ]
