# Generated by Django 2.1.4 on 2018-12-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0017_auto_20181216_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitem',
            name='image_thumb',
            field=models.ImageField(upload_to='images/%Y/%m/'),
        ),
    ]
