# Generated by Django 2.1.4 on 2018-12-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0017_portitem_intro_text'),
        ('gis_portfolio_pieces', '0018_auto_20181217_0042'),
    ]

    operations = [
    ]
