# Generated by Django 2.1.4 on 2018-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0019_merge_20181219_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='portitem',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portitempiece',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
