# Generated by Django 2.1.4 on 2018-12-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0020_auto_20181219_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portitem',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='portitem',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='portitempiece',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='portitempiece',
            name='weight',
        ),
    ]
