# Generated by Django 2.1.4 on 2018-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_portfolio_pieces', '0022_auto_20181219_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portitem',
            name='intro_text',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
